project:
  type: book
  output-dir: docs
  resources:
    - podcast/introducao_dialogo_eleven_v3.mp3
    - podcast/introducao.md
    - podcast/introducao_dialogo_eleven_v3_transcript.json
    - podcast/historico_dialogo_eleven_v3.mp3
    - podcast/historico.md
    - podcast/historico_dialogo_eleven_v3_transcript.json
    - podcast/organizacao_dialogo_eleven_v3.mp3
    - podcast/organizacao.md
    - podcast/organizacao_dialogo_eleven_v3_transcript.json
    - podcast/eventos_dialogo_eleven_v3.mp3
    - podcast/eventos.md
    - podcast/eventos_dialogo_eleven_v3_transcript.json
    - podcast/sim.mp3
    - podcast/sim.md
    - podcast/sim_transcript.json
    - podcast/sinasc.mp3
    - podcast/sinasc.md
    - podcast/sinasc_transcript.json
    - podcast/sih.mp3
    - podcast/sih.md
    - podcast/sih_transcript.json
    - podcast/sia.mp3
    - podcast/sia.md
    - podcast/sia_transcript.json
    - podcast/sinan_dialogo_eleven_v3.mp3
    - podcast/sinan.md
    - podcast/sinan_dialogo_eleven_v3_transcript.json
    - podcast/cnes.mp3
    - podcast/cnes.md
    - podcast/cnes_transcript.json
    - podcast/siops.mp3
    - podcast/siops.md
    - podcast/siops_transcript.json
    - podcast/sisaps.mp3
    - podcast/sisaps.md
    - podcast/sisaps_transcript.json
    - podcast/sisagua.mp3
    - podcast/sisagua.md
    - podcast/sisagua_transcript.json
    - podcast/sipni.mp3
    - podcast/sipni.md
    - podcast/sipni_transcript.json
    - podcast/rnds.mp3
    - podcast/rnds.md
    - podcast/rnds_transcript.json
    - podcast/sync-transcript.js

execute:
  freeze: auto

lang: pt 
language:
  title-block-published: "Data da Última Atualização"

book:
  title: "Sistemas de Informação em Saúde no Brasil"
  author: "Raphael de Freitas Saldanha"
  isbn: "978-65-01-37841-1"
  description: "E-book sobre os principais Sistemas de Informação em Saúde no Brasil."
  site-url: "https://rfsaldanha.github.io/sis/"
  repo-url: "https://github.com/rfsaldanha/sis"
  repo-actions: [source, issue]
  date: today
  search: true
  downloads: [pdf]
  google-analytics: 
    tracking-id: G-2M7VLSRDCB
    anonymize-ip: false
  chapters:
    - index.qmd
    - introducao.qmd
    - historico.qmd
    - organizacao.qmd
    - eventos.qmd
    - sim.qmd
    - sinasc.qmd
    - sih.qmd
    - sia.qmd
    - sinan.qmd
    - cnes.qmd
    - sisagua.qmd
    - siops.qmd
    - sisaps.qmd
    - sipni.qmd
    - rnds.qmd
    - referencias.qmd
  appendices:
    - quadro_resumo.qmd
    - cid.qmd
    - codmun.qmd
    - pop.qmd
    - sivep.qmd
    - sisvan.qmd
    - ans.qmd
    #- vigitel.qmd
    #- pns.qmd
    #- rnds.qmd
    #- esus-not.qmd


bibliography: references.bib
csl: abnt.csl

format:
  html:
    theme:
      light: journal
      dark: darkly
    css: styles.css
  pdf:
   documentclass: scrreprt
