project:
  type: book
  output-dir: docs

execute:
  freeze: false

lang: pt 

book:
  title: "Sistemas de Informações em Saúde"
  author: "Raphael de Freitas Saldanha"
  date: today
  search: true
  downloads: [pdf, epub]
  chapters:
    - index.qmd
    - intro.qmd
    - organizacao.qmd
    - historico.qmd
    - sim.qmd
    - sinasc.qmd
    - sih.qmd
    - sia.qmd
    - cnes.qmd
    - siab.qmd
    - sinan.qmd
    - sivep.qmd
    - siops.qmd
    - referencias.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt



