project:
  type: book
  output-dir: docs

execute:
  freeze: auto

lang: pt 

book:
  title: "Sistemas de Informação em Saúde no Brasil"
  author: "Raphael de Freitas Saldanha"
  isbn: "978-65-01-37841-1"
  date: today
  search: true
  downloads: [pdf, epub]
  google-analytics: 
    tracking-id: G-2M7VLSRDCB
    anonymize-ip: false
  chapters:
    - index.qmd
    - introducao.qmd
    - historico.qmd
    - organizacao.qmd
    - eventos.qmd
    - sim.qmd
    - sinasc.qmd
    - sih.qmd
    - sia.qmd
    - sinan.qmd
    - cnes.qmd
    - siops.qmd
    - sisagua.qmd
    - sisab.qmd
    - sipni.qmd
    - referencias.qmd
  appendices:
    - cid.qmd
    - codmun.qmd
    - pop.qmd
    - sivep.qmd
    - sisvan.qmd
    - ans.qmd
    #- vigitel.qmd
    #- pns.qmd
    #- rnds.qmd
    #- esus-not.qmd


bibliography: references.bib
csl: abnt.csl

format:
  html:
    theme:
      light: journal
      dark: darkly
  pdf:
   documentclass: scrreprt
  epub: 
   toc: true
