project:
  type: book
  output-dir: docs

execute:
  freeze: auto

lang: pt 

book:
  title: "Sistemas de Informações em Saúde do Brasil"
  author: "Raphael de Freitas Saldanha"
  date: today
  doi: 10.5281/zenodo.14933369
  issn: xxx
  search: true
  downloads: [pdf, epub]
  google-analytics: G-2M7VLSRDCB
  chapters:
    - index.qmd
    - introducao.qmd
    - historico.qmd
    - sim.qmd
    - sinasc.qmd
    - sih.qmd
    - sia.qmd
    - sinan.qmd
    - cnes.qmd
    - siab.qmd
    - sivep.qmd
    - sisvan.qmd
    - sisagua.qmd
    - siops.qmd
    - sipni.qmd
    - referencias.qmd
  appendices:
    - cid.qmd
    - pop.qmd
    - pns.qmd
    - rnds.qmd

bibliography: references.bib
csl: abnt.csl

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt
  epub: 
    toc: true



