<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="pt" xml:lang="pt"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="description" content="Livro sobre os principais Sistemas de Informação em Saúde no Brasil.">

<title>Apêndice G — Agência Nacional de Saúde Suplementar - ANS – Sistemas de Informação em Saúde no Brasil</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 1em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./interoperabilidade.html" rel="next">
<link href="./sisvan.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark-0a6b7249c26820e032cb0bd839ff02b1.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-54427c74024eba8e34e34421ce4d6b49.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark-aa873432a3c62897e6c2091c0d30a948.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="site_libs/bootstrap/bootstrap-54427c74024eba8e34e34421ce4d6b49.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Nenhum resultado",
    "search-matching-documents-text": "documentos correspondentes",
    "search-copy-link-title": "Copiar link para a busca",
    "search-hide-matches-text": "Esconder correspondências adicionais",
    "search-more-match-text": "mais correspondência neste documento",
    "search-more-matches-text": "mais correspondências neste documento",
    "search-clear-button-title": "Limpar",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancelar",
    "search-submit-button-title": "Enviar",
    "search-label": "Procurar"
  }
}</script>
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-2M7VLSRDCB"></script>

<script type="text/javascript">

window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'G-2M7VLSRDCB', { 'anonymize_ip': false});
</script>


<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-sidebar floating quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./quadro_resumo.html">Apêndices</a></li><li class="breadcrumb-item"><a href="./ans.html"><span class="chapter-number">G</span>&nbsp; <span class="chapter-title">Agência Nacional de Saúde Suplementar - ANS</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Procurar" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Sistemas de Informação em Saúde no Brasil</a> 
        <div class="sidebar-tools-main tools-wide">
    <a href="https://github.com/rfsaldanha/sis" title="Código fonte" class="quarto-navigation-tool px-1" aria-label="Código fonte"><i class="bi bi-github"></i></a>
    <a href="./Sistemas-de-Informação-em-Saúde-no-Brasil.pdf" title="Download PDF" class="quarto-navigation-tool px-1" aria-label="Download PDF"><i class="bi bi-file-pdf"></i></a>
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Alternar modo escuro"><i class="bi"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Procurar"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Bem-vindo</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./siglas.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lista de siglas</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./introducao.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introdução</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./historico.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Breve histórico da experiência brasileira</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./organizacao.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Organização dos SIS</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./eventos.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Eventos de saúde</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./sim.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">SIM – Sistema de Informação sobre Mortalidade</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./sinasc.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">SINASC – Sistema de Informação sobre Nascidos Vivos</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./sih.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">SIH – Sistema de Informações Hospitalares do SUS</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./sia.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">SIA – Sistema de Informações Ambulatoriais do SUS</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./sinan.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">SINAN – Sistema de Informação de Agravos de Notificação</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./cnes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">CNES – Cadastro Nacional de Estabelecimentos de Saúde</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./sisagua.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">SISAGUA – Sistema de Informação de Vigilância da Qualidade da Água para Consumo Humano</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./siops.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">SIOPS – Sistema de Informações sobre Orçamentos Públicos em Saúde</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./sisaps.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">SISAPS - Sistema de Informação para a Atenção Primária à Saúde</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./sipni.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">SI-PNI – Sistema de Informações do Programa Nacional de Imunizações</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./rnds.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">RNDS – Rede Nacional de Dados em Saúde</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./referencias.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Referências</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Apêndices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Alternar seção">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./quadro_resumo.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Quadro resumo</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./cid.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">CID – Classificação Internacional de Doenças</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./codmun.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">Códigos dos municípios</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./pop.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">D</span>&nbsp; <span class="chapter-title">Estimativas populacionais</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./sivep.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">E</span>&nbsp; <span class="chapter-title">SIVEP – Sistema de Vigilância Epidemiológica</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./sisvan.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">F</span>&nbsp; <span class="chapter-title">SISVAN – Sistema de Vigilância Alimentar e Nutricional</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ans.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">G</span>&nbsp; <span class="chapter-title">Agência Nacional de Saúde Suplementar - ANS</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container">
  <a href="./interoperabilidade.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">H</span>&nbsp; <span class="chapter-title">Interoperabilidade entre os Sistemas de Informação em Saúde</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container">
  <a href="./indice.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Índice remissivo</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Índice</h2>

  <ul>
  <li><a href="#criação-e-principais-marcos-regulatórios" id="toc-criação-e-principais-marcos-regulatórios" class="nav-link active" data-scroll-target="#criação-e-principais-marcos-regulatórios"><span class="header-section-number">G.1</span> Criação e principais marcos regulatórios</a></li>
  <li><a href="#para-que-serve-a-ans" id="toc-para-que-serve-a-ans" class="nav-link" data-scroll-target="#para-que-serve-a-ans"><span class="header-section-number">G.2</span> Para que serve a ANS</a></li>
  <li><a href="#sistemas-e-fluxos-de-informação-da-saúde-suplementar" id="toc-sistemas-e-fluxos-de-informação-da-saúde-suplementar" class="nav-link" data-scroll-target="#sistemas-e-fluxos-de-informação-da-saúde-suplementar"><span class="header-section-number">G.3</span> Sistemas e fluxos de informação da saúde suplementar</a></li>
  <li><a href="#dados-abertos-e-formas-de-acesso" id="toc-dados-abertos-e-formas-de-acesso" class="nav-link" data-scroll-target="#dados-abertos-e-formas-de-acesso"><span class="header-section-number">G.4</span> Dados abertos e formas de acesso</a></li>
  <li><a href="#integração-com-dados-dos-sis" id="toc-integração-com-dados-dos-sis" class="nav-link" data-scroll-target="#integração-com-dados-dos-sis"><span class="header-section-number">G.5</span> Integração com dados dos SIS</a>
  <ul class="collapse">
  <li><a href="#coberturas-que-não-são-equivalentes" id="toc-coberturas-que-não-são-equivalentes" class="nav-link" data-scroll-target="#coberturas-que-não-são-equivalentes"><span class="header-section-number">G.5.1</span> Coberturas que não são equivalentes</a></li>
  <li><a href="#ressarcimento-ao-sus-como-integração-institucional" id="toc-ressarcimento-ao-sus-como-integração-institucional" class="nav-link" data-scroll-target="#ressarcimento-ao-sus-como-integração-institucional"><span class="header-section-number">G.5.2</span> Ressarcimento ao SUS como integração institucional</a></li>
  <li><a href="#estratégias-de-integração-analítica" id="toc-estratégias-de-integração-analítica" class="nav-link" data-scroll-target="#estratégias-de-integração-analítica"><span class="header-section-number">G.5.3</span> Estratégias de integração analítica</a></li>
  <li><a href="#cuidados-para-evitar-interpretações-incorretas" id="toc-cuidados-para-evitar-interpretações-incorretas" class="nav-link" data-scroll-target="#cuidados-para-evitar-interpretações-incorretas"><span class="header-section-number">G.5.4</span> Cuidados para evitar interpretações incorretas</a></li>
  </ul></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/rfsaldanha/sis/blob/main/ans.qmd" class="toc-action"><i class="bi bi-github"></i>Ver o código fonte</a></li><li><a href="https://github.com/rfsaldanha/sis/issues/new" class="toc-action"><i class="bi empty"></i>Criar uma issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">


<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./quadro_resumo.html">Apêndices</a></li><li class="breadcrumb-item"><a href="./ans.html"><span class="chapter-number">G</span>&nbsp; <span class="chapter-title">Agência Nacional de Saúde Suplementar - ANS</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span id="sec-ans" class="quarto-section-identifier">Apêndice G — Agência Nacional de Saúde Suplementar - ANS</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>A Agência Nacional de Saúde Suplementar (ANS) é a agência reguladora federal responsável pelo setor de planos privados de assistência à saúde. Vinculada ao Ministério da Saúde, ela é uma autarquia sob regime especial, com autonomia administrativa, financeira e técnica, sede no Rio de Janeiro e atuação em todo o território nacional. A Lei nº 9.961, de 28 de janeiro de 2000, atribuiu-lhe funções de regulação, normatização, controle e fiscalização das atividades que garantem a assistência suplementar à saúde <span class="citation" data-cites="brasilLei99612000">(<a href="referencias.html#ref-brasilLei99612000" role="doc-biblioref">BRASIL, 2000</a>)</span>.</p>
<table class="caption-top table">
<caption>Características gerais da ANS</caption>
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Característica</th>
<th>Descrição</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Criação</td>
<td>Lei nº 9.961, de 28 de janeiro de 2000</td>
</tr>
<tr class="even">
<td>Natureza</td>
<td>Autarquia federal sob regime especial, vinculada ao Ministério da Saúde</td>
</tr>
<tr class="odd">
<td>Sede</td>
<td>Rio de Janeiro</td>
</tr>
<tr class="even">
<td>Setor regulado</td>
<td>Operadoras e planos privados de assistência médica, hospitalar e odontológica</td>
</tr>
<tr class="odd">
<td>Objetivo institucional</td>
<td>Defender o interesse público na assistência suplementar à saúde e regular as relações entre operadoras, prestadores e beneficiários</td>
</tr>
<tr class="even">
<td>Fontes de informação</td>
<td>Cadastros de operadoras, planos e beneficiários; dados assistenciais, econômico-financeiros, de fiscalização e de ressarcimento ao SUS</td>
</tr>
<tr class="odd">
<td>Formas públicas de acesso</td>
<td>Dados abertos, arquivos para transferência, TabNet, painéis e publicações setoriais</td>
</tr>
</tbody>
</table>
<p>O campo de atuação da Agência precisa ser delimitado com precisão. A ANS não regula diretamente toda consulta, clínica ou hospital privado do país. Sua competência está concentrada nas relações organizadas por planos privados de assistência à saúde: autorização e acompanhamento de operadoras e produtos, coberturas contratadas, garantias dos beneficiários, rede assistencial, equilíbrio econômico-financeiro, padrões de informação e fiscalização. Serviços privados pagos diretamente pelas pessoas, sem intermediação de um plano, não passam a integrar o setor regulado apenas por serem privados.</p>
<p>Também não há oposição simples entre “população do SUS” e “população dos planos”. O SUS é universal, e possuir um plano não retira o direito de utilizar serviços públicos. Uma mesma pessoa pode receber atenção financiada pela operadora em determinado momento e pelo SUS em outro. Essa sobreposição é decisiva para interpretar dados da ANS e para integrá-los aos SIS.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Saúde suplementar e participação complementar">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Saúde suplementar e participação complementar
</div>
</div>
<div class="callout-body-container callout-body">
<p>Saúde suplementar designa a assistência intermediada por planos privados. Ela não é sinônimo de toda assistência privada nem da participação complementar de estabelecimentos privados contratados pelo SUS.</p>
</div>
</div>
<section id="criação-e-principais-marcos-regulatórios" class="level2" data-number="G.1">
<h2 data-number="G.1" class="anchored" data-anchor-id="criação-e-principais-marcos-regulatórios"><span class="header-section-number">G.1</span> Criação e principais marcos regulatórios</h2>
<p>A Constituição Federal de 1988 consolidou a saúde como direito de todos e dever do Estado, instituiu as bases do SUS e permitiu a atuação da iniciativa privada na assistência à saúde. Durante a década seguinte, o mercado de planos operou sem uma agência setorial e com regras fragmentadas, embora seguradoras já estivessem submetidas ao controle econômico-financeiro da Superintendência de Seguros Privados.</p>
<p>A Lei nº 9.656, de 3 de junho de 1998, estabeleceu o marco legal dos planos e seguros privados de assistência à saúde. A norma definiu produtos e operadoras, instituiu exigências de cobertura e contratação, disciplinou registros e criou a obrigação de ressarcimento ao SUS pelos atendimentos sujeitos aos critérios legais <span class="citation" data-cites="brasilLei96561998">(<a href="referencias.html#ref-brasilLei96561998" role="doc-biblioref">BRASIL, 1998</a>)</span>. Dois anos depois, a Lei nº 9.961/2000 criou a ANS e reuniu em uma agência especializada a regulação assistencial e econômico-financeira do setor.</p>
<table class="caption-top table">
<caption>Marcos selecionados da regulação da saúde suplementar</caption>
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Ano</th>
<th>Marco</th>
<th>Efeito principal</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1988</td>
<td>Constituição Federal</td>
<td>Afirma a universalidade do SUS e a liberdade de atuação privada em saúde nos limites legais</td>
</tr>
<tr class="even">
<td>1998</td>
<td>Lei nº 9.656</td>
<td>Regulamenta os planos privados, coberturas, contratos, operadoras e ressarcimento ao SUS</td>
</tr>
<tr class="odd">
<td>2000</td>
<td>Lei nº 9.961</td>
<td>Cria a ANS como autarquia especial vinculada ao Ministério da Saúde</td>
</tr>
<tr class="even">
<td>2005</td>
<td>Instituição do padrão TISS</td>
<td>Padroniza trocas eletrônicas entre operadoras e prestadores e amplia a produção de informação assistencial</td>
</tr>
<tr class="odd">
<td>2011 e 2022</td>
<td>Garantia de atendimento</td>
<td>Estabelece e consolida prazos e responsabilidades para acesso dos beneficiários aos serviços cobertos</td>
</tr>
<tr class="even">
<td>2019</td>
<td>Lei nº 13.848</td>
<td>Uniformiza regras de gestão, decisão, transparência e controle social das agências reguladoras</td>
</tr>
<tr class="odd">
<td>2022</td>
<td>Leis nº 14.307 e nº 14.454</td>
<td>Reformulam o processo de atualização do Rol e definem critérios legais para coberturas não incluídas na lista</td>
</tr>
</tbody>
</table>
<p>O padrão de Troca de Informações na Saúde Suplementar (TISS), instituído em 2005 e atualizado ao longo do tempo, tornou obrigatória a padronização das trocas eletrônicas de dados de atenção à saúde entre os agentes do setor. Ele organiza componentes, mensagens e terminologias usados por prestadores e operadoras, subsidia o acompanhamento assistencial e econômico e tem a interoperabilidade com sistemas do Ministério da Saúde entre suas diretrizes <span class="citation" data-cites="ansTISS2026">(<a href="referencias.html#ref-ansTISS2026" role="doc-biblioref">AGÊNCIA NACIONAL DE SAÚDE SUPLEMENTAR, 2026a</a>)</span>. A Terminologia Unificada da Saúde Suplementar (TUSS) integra esse padrão e identifica procedimentos, itens e conceitos empregados nas transações.</p>
<p>A garantia de atendimento foi outro marco relevante. A Resolução Normativa nº 259/2011 definiu prazos máximos e responsabilidades das operadoras, e suas regras foram consolidadas pela Resolução Normativa nº 566/2022. O cumprimento é acompanhado por reclamações, indicadores e medidas regulatórias, que podem incluir a suspensão temporária da comercialização de planos quando houver risco assistencial reiterado <span class="citation" data-cites="ansRN5662022">(<a href="referencias.html#ref-ansRN5662022" role="doc-biblioref">AGÊNCIA NACIONAL DE SAÚDE SUPLEMENTAR, 2022</a>)</span>.</p>
<p>Em 2019, a Lei nº 13.848 estabeleceu regras gerais para as agências reguladoras federais, incluindo análise de impacto regulatório, transparência decisória, participação social, prestação de contas e mandatos dos dirigentes <span class="citation" data-cites="brasilLei138482019">(<a href="referencias.html#ref-brasilLei138482019" role="doc-biblioref">BRASIL, 2019</a>)</span>. Em 2022, a Lei nº 14.307 reorganizou o processo de avaliação e atualização do Rol de Procedimentos e Eventos em Saúde Suplementar <span class="citation" data-cites="brasilLei143072022">(<a href="referencias.html#ref-brasilLei143072022" role="doc-biblioref">BRASIL, 2022a</a>)</span>. A Lei nº 14.454 passou a definir o Rol como referência básica e estabeleceu critérios para cobertura de procedimentos prescritos que não estejam nele, nas condições previstas pela legislação <span class="citation" data-cites="brasilLei144542022">(<a href="referencias.html#ref-brasilLei144542022" role="doc-biblioref">BRASIL, 2022b</a>)</span>.</p>
<div class="callout callout-style-default callout-warning callout-titled" title="Normas em atualização">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Aviso</span>Normas em atualização
</div>
</div>
<div class="callout-body-container callout-body">
<p>O estoque regulatório da ANS é atualizado e consolidado periodicamente. Para decisões assistenciais, contratuais ou jurídicas, consulte a norma vigente e não apenas o ano do marco histórico apresentado neste apêndice.</p>
</div>
</div>
</section>
<section id="para-que-serve-a-ans" class="level2" data-number="G.2">
<h2 data-number="G.2" class="anchored" data-anchor-id="para-que-serve-a-ans"><span class="header-section-number">G.2</span> Para que serve a ANS</h2>
<p>A finalidade legal da Agência é promover a defesa do interesse público na assistência suplementar à saúde, regulando as operadoras e contribuindo para o desenvolvimento das ações de saúde no país. Isso envolve interesses que podem entrar em tensão: acesso e proteção dos beneficiários, qualidade assistencial, sustentabilidade das operadoras, remuneração e organização da rede prestadora, concorrência e articulação com o SUS.</p>
<table class="caption-top table">
<caption>Principais áreas de atuação da ANS</caption>
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Área de atuação</th>
<th>Exemplos de atividades</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Entrada e permanência no mercado</td>
<td>Registrar operadoras, autorizar produtos, acompanhar condições de funcionamento e adotar regimes especiais</td>
</tr>
<tr class="even">
<td>Cobertura e acesso</td>
<td>Definir o Rol, segmentações assistenciais, regras contratuais, rede e garantia de atendimento</td>
</tr>
<tr class="odd">
<td>Proteção do beneficiário</td>
<td>Receber reclamações, realizar intermediação, fiscalizar negativas e aplicar sanções</td>
</tr>
<tr class="even">
<td>Regulação econômica</td>
<td>Acompanhar solvência, provisões, demonstrações contábeis e reajustes sujeitos à competência da Agência</td>
</tr>
<tr class="odd">
<td>Qualidade</td>
<td>Avaliar desempenho de operadoras, atenção à saúde, acesso, sustentabilidade e qualidade dos dados</td>
</tr>
<tr class="even">
<td>Informação e interoperabilidade</td>
<td>Manter cadastros, estabelecer TISS e TUSS e receber dados periódicos das operadoras</td>
</tr>
<tr class="odd">
<td>Relação com o SUS</td>
<td>Identificar atendimentos de beneficiários no SUS, processar o ressarcimento e produzir informações setoriais</td>
</tr>
</tbody>
</table>
<p>A Agência registra operadoras e planos, acompanha alterações de rede, monitora garantias financeiras e pode determinar medidas corretivas quando identifica problemas assistenciais ou econômico-financeiros. O Rol delimita a referência de cobertura obrigatória conforme a segmentação do produto, enquanto regras de garantia de atendimento tratam da disponibilidade do serviço dentro dos prazos e da área aplicáveis.</p>
<p>Na relação com os beneficiários, a ANS disponibiliza canais de informação e recebe demandas contra operadoras. A Notificação de Intermediação Preliminar (NIP) busca solucionar conflitos de natureza assistencial ou não assistencial antes da abertura de processo sancionador. Reclamações, sua resolutividade e seu desfecho também alimentam indicadores de monitoramento.</p>
<p>O Índice de Desempenho da Saúde Suplementar (IDSS) sintetiza dimensões relacionadas à qualidade da atenção, garantia de acesso, sustentabilidade e gestão de processos e regulação. Ele não deve ser interpretado como uma medida direta e isolada da qualidade de todos os serviços de uma operadora: depende dos indicadores selecionados, das regras do ano-base e da qualidade das informações enviadas.</p>
</section>
<section id="sistemas-e-fluxos-de-informação-da-saúde-suplementar" class="level2" data-number="G.3">
<h2 data-number="G.3" class="anchored" data-anchor-id="sistemas-e-fluxos-de-informação-da-saúde-suplementar"><span class="header-section-number">G.3</span> Sistemas e fluxos de informação da saúde suplementar</h2>
<p>A regulação depende de diferentes sistemas, pois beneficiário, plano, operadora, atendimento e situação financeira são unidades distintas. A existência de um padrão comum não transforma esses registros em uma única base nem elimina diferenças de finalidade.</p>
<table class="caption-top table">
<caption>Fontes de informação usadas na regulação da saúde suplementar</caption>
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Fonte</th>
<th>Conteúdo principal</th>
<th>Unidade ou lógica de registro</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Sistema de Informações de Beneficiários (SIB)</td>
<td>Identificação, endereço e vínculo contratual dos beneficiários</td>
<td>Vínculo entre beneficiário, produto, contratante e operadora</td>
</tr>
<tr class="even">
<td>Cadastro de Operadoras</td>
<td>Registro, modalidade, endereço e situação cadastral</td>
<td>Operadora</td>
</tr>
<tr class="odd">
<td>Registro de Produtos</td>
<td>Segmentação, abrangência, contratação e características do plano</td>
<td>Produto ou plano registrado</td>
</tr>
<tr class="even">
<td>TISS</td>
<td>Guias, eventos assistenciais, procedimentos e valores trocados entre prestadores e operadoras</td>
<td>Evento ou item assistencial, segundo a mensagem e o componente</td>
</tr>
<tr class="odd">
<td>Sistema de Informações de Produtos (SIP)</td>
<td>Produção assistencial agregada informada pelas operadoras</td>
<td>Agregado periódico por operadora e item assistencial</td>
</tr>
<tr class="even">
<td>Documento de Informações Periódicas das Operadoras de Planos de Assistência à Saúde (DIOPS)</td>
<td>Demonstrações e informações econômico-financeiras</td>
<td>Operadora e período contábil</td>
</tr>
<tr class="odd">
<td>Fiscalização e NIP</td>
<td>Demandas, reclamações, intermediações e processos</td>
<td>Demanda ou processo regulatório</td>
</tr>
<tr class="even">
<td>Ressarcimento ao SUS</td>
<td>Atendimentos identificados, avisos, impugnações, cobranças e pagamentos</td>
<td>Atendimento de beneficiário no SUS e processo administrativo</td>
</tr>
</tbody>
</table>
<p>O SIB recebe atualizações cadastrais mensais das operadoras. Sua lógica é de vínculos, não necessariamente de pessoas únicas: alguém associado a dois produtos pode ter dois registros e dois códigos de controle operacional. Por isso, totais divulgados como “beneficiários” precisam ser lidos segundo a definição do conjunto consultado, especialmente em análises de cobertura populacional <span class="citation" data-cites="ansSIB2024">(<a href="referencias.html#ref-ansSIB2024" role="doc-biblioref">AGÊNCIA NACIONAL DE SAÚDE SUPLEMENTAR, 2024</a>)</span>.</p>
<p>O TISS registra transações assistenciais com granularidade diferente do SIP e do DIOPS. A comparação entre o total de despesas informado no TISS e as demonstrações econômico-financeiras é, inclusive, usada para monitorar completude. A ANS alerta que inconsistências identificadas nos dados enviados pelas operadoras podem afetar análises e visualizações, e mantém processos de monitoramento e correção <span class="citation" data-cites="ansTISSDados2026">(<a href="referencias.html#ref-ansTISSDados2026" role="doc-biblioref">AGÊNCIA NACIONAL DE SAÚDE SUPLEMENTAR, 2026e</a>)</span>.</p>
</section>
<section id="dados-abertos-e-formas-de-acesso" class="level2" data-number="G.4">
<h2 data-number="G.4" class="anchored" data-anchor-id="dados-abertos-e-formas-de-acesso"><span class="header-section-number">G.4</span> Dados abertos e formas de acesso</h2>
<p>A ANS publica dados em formatos e interfaces distintos. Alguns conjuntos são arquivos processáveis por máquina; outros são consultas agregadas, painéis ou publicações. O calendário de atualização, a granularidade, o período disponível e as regras de revisão variam entre os produtos. A página institucional de dados abertos apresenta o plano de abertura, o inventário e o cronograma de novos conjuntos <span class="citation" data-cites="ansDadosAbertos2026">(<a href="referencias.html#ref-ansDadosAbertos2026" role="doc-biblioref">AGÊNCIA NACIONAL DE SAÚDE SUPLEMENTAR, 2026b</a>)</span>, enquanto a área de dados e indicadores organiza os acessos por tema <span class="citation" data-cites="ansDadosIndicadores2026">(<a href="referencias.html#ref-ansDadosIndicadores2026" role="doc-biblioref">AGÊNCIA NACIONAL DE SAÚDE SUPLEMENTAR, 2026c</a>)</span>.</p>
<p>Os principais pontos de entrada são:</p>
<ul>
<li><p><a href="https://www.gov.br/ans/pt-br/acesso-a-informacao/perfil-do-setor/dados-abertos-1">Página de Dados Abertos da ANS</a>, com plano, inventário e orientações.</p></li>
<li><p><a href="https://dados.gov.br/dados/organizacoes/visualizar/agencia-nacional-de-saude-suplementar">Conjuntos da ANS no Portal Brasileiro de Dados Abertos</a>, com metadados e recursos para transferência.</p></li>
<li><p><a href="https://www.gov.br/ans/pt-br/acesso-a-informacao/perfil-do-setor/dados-e-indicadores-do-setor">Dados e Indicadores do Setor</a>, que reúne beneficiários, operadoras, planos, dados assistenciais, financeiros e painéis.</p></li>
<li><p><a href="https://www.ans.gov.br/anstabnet/">TabNet da ANS</a>, para tabulações agregadas de beneficiários, operadoras, produtos, receitas e despesas.</p></li>
<li><p><a href="https://dadosabertos.ans.gov.br/FTP/">Diretório de arquivos abertos da ANS</a>, destinado à transferência de bases, dicionários e arquivos históricos.</p></li>
<li><p><a href="https://www.gov.br/ans/pt-br/assuntos/prestadores/padrao-para-troca-de-informacao-de-saude-suplementar-2013-tiss">Padrão TISS</a>, com documentação técnica, componentes e versões do padrão.</p></li>
<li><p><a href="https://www.gov.br/ans/pt-br/acesso-a-informacao/perfil-do-setor/dados-e-indicadores-do-setor/dados-e-publicacoes-do-ressarcimento-ao-sus">Dados e Publicações do Ressarcimento ao SUS</a>, com bases, painéis e boletins sobre atendimentos de beneficiários no SUS.</p></li>
</ul>
<p>Entre os conjuntos mais úteis estão os de beneficiários por município, faixa etária, sexo, operadora, modalidade e tipo de contratação; cadastros de operadoras ativas e canceladas; características e abrangência dos planos; rede de prestadores; procedimentos ambulatoriais e hospitalares informados pelo TISS; produção assistencial do SIP; demonstrações contábeis; receitas e despesas; reajustes; reclamações; IDSS; e ressarcimento ao SUS.</p>
<table class="caption-top table">
<caption>Usos e limites de grupos de dados divulgados pela ANS</caption>
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Grupo de dados</th>
<th>Perguntas possíveis</th>
<th>Cuidados principais</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Beneficiários</td>
<td>Quantos vínculos ativos existem e como se distribuem?</td>
<td>Vínculo não é sempre pessoa única; competência e endereço podem mudar</td>
</tr>
<tr class="even">
<td>Operadoras e planos</td>
<td>Quem está ativo, que produtos oferece e em qual abrangência?</td>
<td>Situação cadastral e comercialização variam no tempo</td>
</tr>
<tr class="odd">
<td>TISS</td>
<td>Que procedimentos e despesas foram informados no setor suplementar?</td>
<td>Dados públicos podem ser agregados; completude e revisões variam por operadora e período</td>
</tr>
<tr class="even">
<td>SIP</td>
<td>Qual a produção assistencial agregada das operadoras?</td>
<td>Conceitos e nível de agregação diferem do TISS</td>
</tr>
<tr class="odd">
<td>Econômico-financeiros</td>
<td>Como evoluem receitas, despesas e solvência?</td>
<td>Regime contábil não equivale à data clínica do atendimento</td>
</tr>
<tr class="even">
<td>Qualidade e reclamações</td>
<td>Como operadoras se comparam nos indicadores regulatórios?</td>
<td>Metodologia, elegibilidade e ano-base precisam acompanhar o resultado</td>
</tr>
<tr class="odd">
<td>Ressarcimento ao SUS</td>
<td>Que atendimentos de beneficiários foram identificados e cobrados?</td>
<td>Identificação, cobrança, pagamento e atendimento são etapas diferentes</td>
</tr>
</tbody>
</table>
<p>Os produtos públicos não expõem toda a base operacional. Informações pessoais do SIB e registros individualizados de atenção são protegidos; arquivos públicos podem estar agregados, anonimizados ou ter variáveis selecionadas. A ausência de identificadores limita o relacionamento individual com outros SIS, mas ainda permite integração por município, período, estabelecimento, operadora, faixa etária ou categoria de procedimento.</p>
</section>
<section id="integração-com-dados-dos-sis" class="level2" data-number="G.5">
<h2 data-number="G.5" class="anchored" data-anchor-id="integração-com-dados-dos-sis"><span class="header-section-number">G.5</span> Integração com dados dos SIS</h2>
<section id="coberturas-que-não-são-equivalentes" class="level3" data-number="G.5.1">
<h3 data-number="G.5.1" class="anchored" data-anchor-id="coberturas-que-não-são-equivalentes"><span class="header-section-number">G.5.1</span> Coberturas que não são equivalentes</h3>
<p>A primeira decisão ao integrar ANS e SIS é definir quem e o que cada fonte observa. SIH/SUS e SIA/SUS registram produção financiada pelo SUS: internações autorizadas por AIH e procedimentos ambulatoriais captados por APAC, BPA e outros instrumentos. Um hospital privado conveniado pode aparecer nesses sistemas quando presta atendimento financiado pelo SUS; portanto, “dado do SUS” não significa necessariamente “prestador público”.</p>
<p>O SISAB e o Siaps descrevem atividades da APS no SUS em períodos e arranjos operacionais distintos. Em contraste, TISS e SIP refletem atenção intermediada por operadoras. Consultas e procedimentos privados pagos diretamente pelas famílias podem ficar fora dos dois domínios, pois não foram financiados pelo SUS nem por um plano.</p>
<p>Nem todos os SIS, contudo, se restringem à dimensão pública. SIM e SINASC têm pretensão nacional e registram óbitos e nascimentos ocorridos nos setores público e privado. SINAN recebe notificações compulsórias originadas em serviços públicos e privados. O CNES cadastra estabelecimentos de diferentes naturezas e vínculos. Essas fontes podem funcionar como referências nacionais ou pontes de integração, embora sua cobertura e qualidade precisem ser avaliadas em cada uso.</p>
<table class="caption-top table">
<caption>Possibilidades e limites da integração entre dados da ANS e SIS</caption>
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Fonte da ANS</th>
<th>SIS relacionado</th>
<th>O que a combinação pode mostrar</th>
<th>Limite essencial</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>SIB</td>
<td>SIH/SUS e SIA/SUS</td>
<td>Uso do SUS por pessoas com vínculo a plano e ressarcimento</td>
<td>Beneficiário de plano continua tendo direito ao SUS; as populações se sobrepõem</td>
</tr>
<tr class="even">
<td>TISS</td>
<td>SIH/SUS</td>
<td>Produção hospitalar financiada por planos e pelo SUS</td>
<td>AIH e guia TISS têm conceitos, códigos e regras de pagamento diferentes</td>
</tr>
<tr class="odd">
<td>TISS</td>
<td>SIA/SUS</td>
<td>Procedimentos ambulatoriais nos dois regimes de financiamento</td>
<td>APAC, BPA e mensagens TISS não são unidades diretamente intercambiáveis</td>
</tr>
<tr class="even">
<td>SIB e TISS</td>
<td>SISAB</td>
<td>Relação entre cobertura por planos e produção da APS pública</td>
<td>Dados agregados não demonstram substituição individual entre serviços</td>
</tr>
<tr class="odd">
<td>Rede das operadoras</td>
<td>CNES</td>
<td>Localização, natureza e capacidade dos prestadores</td>
<td>Rede contratada, cadastro ativo e produção realizada são conceitos distintos</td>
</tr>
<tr class="even">
<td>SIB</td>
<td>SIM, SINASC ou SINAN</td>
<td>Desfechos e eventos entre beneficiários, mediante governança</td>
<td>Esses SIS não representam apenas a dimensão pública e o vínculo individual exige dados protegidos</td>
</tr>
</tbody>
</table>
</section>
<section id="ressarcimento-ao-sus-como-integração-institucional" class="level3" data-number="G.5.2">
<h3 data-number="G.5.2" class="anchored" data-anchor-id="ressarcimento-ao-sus-como-integração-institucional"><span class="header-section-number">G.5.2</span> Ressarcimento ao SUS como integração institucional</h3>
<p>O ressarcimento é o exemplo mais concreto de integração entre bases da saúde suplementar e SIS de produção pública. A ANS relaciona o cadastro de vínculos do SIB com registros de internações do SIH/SUS e procedimentos ambulatoriais de média e alta complexidade do SIA/SUS. Quando um atendimento satisfaz os critérios legais, a operadora recebe um Aviso de Beneficiário Identificado (ABI), pode impugnar a identificação e, concluído o processo, o valor devido é encaminhado ao Fundo Nacional de Saúde <span class="citation" data-cites="ansRessarcimento2026">(<a href="referencias.html#ref-ansRessarcimento2026" role="doc-biblioref">AGÊNCIA NACIONAL DE SAÚDE SUPLEMENTAR, 2026d</a>)</span>.</p>
<p>Esse fluxo mostra que cobertura de plano e utilização do SUS não são categorias excludentes. Também demonstra a diferença entre o dado analítico e o administrativo: atendimento identificado, valor cobrado, decisão definitiva, pagamento e repasse correspondem a etapas diferentes. Somar quantidades dessas etapas ou interpretar todo atendimento de beneficiário no SUS como dívida confirmada produz resultados incorretos.</p>
<p>O relacionamento institucional utiliza informações identificadas e regras protegidas por governança. Os dados públicos de ressarcimento permitem analisar volumes, valores, operadoras, períodos e distribuição dos atendimentos, mas não reproduzem a base nominal empregada no processo. A discussão metodológica sobre interoperabilidade e <em>linkage</em> é aprofundada na <a href="interoperabilidade.html" class="quarto-xref"><span>Apêndice H</span></a>.</p>
</section>
<section id="estratégias-de-integração-analítica" class="level3" data-number="G.5.3">
<h3 data-number="G.5.3" class="anchored" data-anchor-id="estratégias-de-integração-analítica"><span class="header-section-number">G.5.3</span> Estratégias de integração analítica</h3>
<p>Uma análise agregada pode combinar o número de vínculos de beneficiários da ANS com estimativas populacionais para calcular taxa de cobertura por território e período. Essa taxa não deve ser tratada como proporção exata de pessoas com plano quando houver vínculos múltiplos, divergência de competência ou diferenças no endereço. Também não mede uso efetivo: estar vinculado a um plano não informa se a pessoa utilizou sua rede, pagou diretamente ou recorreu ao SUS.</p>
<p>Para comparar utilização, é preferível construir taxas separadas: eventos financiados pelo SUS sobre a população pertinente e eventos da saúde suplementar sobre os vínculos ou beneficiários elegíveis, conforme a definição da fonte. Somar numeradores antes de harmonizar unidades pode duplicar eventos ou misturar internações, autorizações, guias, procedimentos e itens de cobrança. Uma internação pode gerar uma AIH no SIH/SUS e múltiplos itens TISS em outro regime; os registros não representam necessariamente a mesma unidade analítica.</p>
<p>O CNES oferece uma chave útil para estabelecimentos. Ele permite associar natureza jurídica, localização, leitos, equipamentos e profissionais a prestadores informados pelas operadoras, desde que o identificador esteja preenchido e válido para o período. Ainda assim, pertencer à rede de um plano não prova que houve atendimento, e constar no CNES não prova disponibilidade para todos os beneficiários ou para o SUS.</p>
<p>TUSS e SIGTAP exigem mapeamento conceitual. Mesmo quando dois códigos descrevem procedimentos semelhantes, regras de agrupamento, cobertura, faturamento e vigência podem divergir. A comparação deve preservar as versões das tabelas e explicitar se a unidade é procedimento, guia, autorização, atendimento, internação ou pessoa.</p>
</section>
<section id="cuidados-para-evitar-interpretações-incorretas" class="level3" data-number="G.5.4">
<h3 data-number="G.5.4" class="anchored" data-anchor-id="cuidados-para-evitar-interpretações-incorretas"><span class="header-section-number">G.5.4</span> Cuidados para evitar interpretações incorretas</h3>
<ol type="1">
<li><p>Definir a população e o regime de financiamento. Distinguir residentes, vínculos a planos, usuários do SUS, beneficiários atendidos e pessoas únicas.</p></li>
<li><p>Alinhar tempo e território. Compatibilizar competência, data do atendimento, vigência do vínculo, residência do beneficiário e localização do prestador.</p></li>
<li><p>Harmonizar unidades. Não equiparar automaticamente AIH, APAC, BPA, guia TISS, item de procedimento e internação clínica.</p></li>
<li><p>Preservar a sobreposição. Não subtrair todos os beneficiários da população para criar uma suposta “população exclusivamente SUS”; beneficiários também utilizam o sistema público.</p></li>
<li><p>Verificar completude e revisões. Dados recentes do TISS, SIB, SIH/SUS e SIA/SUS podem mudar após correções, reenvios e consolidação.</p></li>
<li><p>Controlar duplicidades. Estabelecimentos, vínculos e eventos podem aparecer mais de uma vez conforme produto, competência, guia ou fonte.</p></li>
<li><p>Respeitar a proteção dos dados. Relacionamento individual exige base legal, finalidade, ambiente seguro, minimização e autorização institucional; microdados públicos agregados não devem ser usados para tentar reidentificar pessoas.</p></li>
<li><p>Documentar o mapeamento. Registrar versões de TUSS, SIGTAP, CNES, regras de inclusão, denominadores e decisões de correspondência.</p></li>
</ol>
<p>Integrar ANS e SIS amplia a capacidade de observar o sistema de saúde brasileiro, mas não cria automaticamente uma base completa da assistência nacional. A combinação cobre partes diferentes do financiamento e da prestação, permanece sujeita a lacunas — especialmente o pagamento privado direto — e precisa preservar a dupla condição de muitas pessoas como beneficiárias de planos e usuárias potenciais do SUS. O resultado mais útil não é uma soma indiscriminada, mas uma análise que torne visíveis as fronteiras, as interseções e as diferenças entre as fontes.</p>


<div id="refs" class="references csl-bib-body" data-entry-spacing="1" role="list" style="display: none">
<div id="ref-ansRN5662022" class="csl-entry" role="listitem">
AGÊNCIA NACIONAL DE SAÚDE SUPLEMENTAR. <strong>Resolução Normativa ANS nº 566, de 29 de dezembro de 2022</strong>. Disponível em: &lt;<a href="https://bvsms.saude.gov.br/bvs/saudelegis/ans/2023/res0566_02_01_2023.html">https://bvsms.saude.gov.br/bvs/saudelegis/ans/2023/res0566_02_01_2023.html</a>&gt;. Acesso em: 15 jul. 2026.
</div>
<div id="ref-ansSIB2024" class="csl-entry" role="listitem">
AGÊNCIA NACIONAL DE SAÚDE SUPLEMENTAR. <strong>Sobre o Sistema de Informações de Beneficiários</strong>. Disponível em: &lt;<a href="https://www.gov.br/ans/pt-br/sobre-o-sib">https://www.gov.br/ans/pt-br/sobre-o-sib</a>&gt;. Acesso em: 15 jul. 2026.
</div>
<div id="ref-ansTISS2026" class="csl-entry" role="listitem">
AGÊNCIA NACIONAL DE SAÚDE SUPLEMENTAR. <strong>TISS: Padrão para Troca de Informação de Saúde Suplementar</strong>. Disponível em: &lt;<a href="https://www.gov.br/ans/pt-br/assuntos/prestadores/padrao-para-troca-de-informacao-de-saude-suplementar-2013-tiss">https://www.gov.br/ans/pt-br/assuntos/prestadores/padrao-para-troca-de-informacao-de-saude-suplementar-2013-tiss</a>&gt;. Acesso em: 15 jul. 2026a.
</div>
<div id="ref-ansDadosAbertos2026" class="csl-entry" role="listitem">
AGÊNCIA NACIONAL DE SAÚDE SUPLEMENTAR. <strong>Dados Abertos</strong>. Disponível em: &lt;<a href="https://www.gov.br/ans/pt-br/acesso-a-informacao/perfil-do-setor/dados-abertos-1">https://www.gov.br/ans/pt-br/acesso-a-informacao/perfil-do-setor/dados-abertos-1</a>&gt;. Acesso em: 15 jul. 2026b.
</div>
<div id="ref-ansDadosIndicadores2026" class="csl-entry" role="listitem">
AGÊNCIA NACIONAL DE SAÚDE SUPLEMENTAR. <strong>Dados e Indicadores do Setor</strong>. Disponível em: &lt;<a href="https://www.gov.br/ans/pt-br/acesso-a-informacao/perfil-do-setor/dados-e-indicadores-do-setor">https://www.gov.br/ans/pt-br/acesso-a-informacao/perfil-do-setor/dados-e-indicadores-do-setor</a>&gt;. Acesso em: 15 jul. 2026c.
</div>
<div id="ref-ansRessarcimento2026" class="csl-entry" role="listitem">
AGÊNCIA NACIONAL DE SAÚDE SUPLEMENTAR. <strong>Dados e Publicações do Ressarcimento ao SUS</strong>. Disponível em: &lt;<a href="https://www.gov.br/ans/pt-br/acesso-a-informacao/perfil-do-setor/dados-e-indicadores-do-setor/dados-e-publicacoes-do-ressarcimento-ao-sus">https://www.gov.br/ans/pt-br/acesso-a-informacao/perfil-do-setor/dados-e-indicadores-do-setor/dados-e-publicacoes-do-ressarcimento-ao-sus</a>&gt;. Acesso em: 15 jul. 2026d.
</div>
<div id="ref-ansTISSDados2026" class="csl-entry" role="listitem">
AGÊNCIA NACIONAL DE SAÚDE SUPLEMENTAR. <strong>ANS atualiza dados abertos do Padrão TISS</strong>. Disponível em: &lt;<a href="https://www.gov.br/ans/pt-br/assuntos/noticias/operadoras/ans-atualiza-dados-abertos-do-padrao-tiss">https://www.gov.br/ans/pt-br/assuntos/noticias/operadoras/ans-atualiza-dados-abertos-do-padrao-tiss</a>&gt;. Acesso em: 15 jul. 2026e.
</div>
<div id="ref-brasilLei96561998" class="csl-entry" role="listitem">
BRASIL. <strong>Lei nº 9.656, de 3 de junho de 1998</strong>. Disponível em: &lt;<a href="https://www.planalto.gov.br/ccivil_03/leis/l9656.htm">https://www.planalto.gov.br/ccivil_03/leis/l9656.htm</a>&gt;. Acesso em: 15 jul. 2026.
</div>
<div id="ref-brasilLei99612000" class="csl-entry" role="listitem">
BRASIL. <strong>Lei nº 9.961, de 28 de janeiro de 2000</strong>. Disponível em: &lt;<a href="https://www.planalto.gov.br/ccivil_03/leis/l9961.htm">https://www.planalto.gov.br/ccivil_03/leis/l9961.htm</a>&gt;. Acesso em: 15 jul. 2026.
</div>
<div id="ref-brasilLei138482019" class="csl-entry" role="listitem">
BRASIL. <strong>Lei nº 13.848, de 25 de junho de 2019</strong>. Disponível em: &lt;<a href="https://www.planalto.gov.br/ccivil_03/_ato2019-2022/2019/lei/l13848.htm">https://www.planalto.gov.br/ccivil_03/_ato2019-2022/2019/lei/l13848.htm</a>&gt;. Acesso em: 15 jul. 2026.
</div>
<div id="ref-brasilLei143072022" class="csl-entry" role="listitem">
BRASIL. <strong>Lei nº 14.307, de 3 de março de 2022</strong>. Disponível em: &lt;<a href="https://www.planalto.gov.br/ccivil_03/_ato2019-2022/2022/lei/l14307.htm">https://www.planalto.gov.br/ccivil_03/_ato2019-2022/2022/lei/l14307.htm</a>&gt;. Acesso em: 15 jul. 2026a.
</div>
<div id="ref-brasilLei144542022" class="csl-entry" role="listitem">
BRASIL. <strong>Lei nº 14.454, de 21 de setembro de 2022</strong>. Disponível em: &lt;<a href="https://www.planalto.gov.br/ccivil_03/_ato2019-2022/2022/lei/l14454.htm">https://www.planalto.gov.br/ccivil_03/_ato2019-2022/2022/lei/l14454.htm</a>&gt;. Acesso em: 15 jul. 2026b.
</div>
</div>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copiada");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copiada");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/rfsaldanha\.github\.io\/sis\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./sisvan.html" class="pagination-link" aria-label="SISVAN -- Sistema de Vigilância Alimentar e Nutricional">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">F</span>&nbsp; <span class="chapter-title">SISVAN – Sistema de Vigilância Alimentar e Nutricional</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./interoperabilidade.html" class="pagination-link" aria-label="Interoperabilidade entre os Sistemas de Informação em Saúde">
        <span class="nav-page-text"><span class="chapter-number">H</span>&nbsp; <span class="chapter-title">Interoperabilidade entre os Sistemas de Informação em Saúde</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/rfsaldanha/sis/blob/main/ans.qmd" class="toc-action"><i class="bi bi-github"></i>Ver o código fonte</a></li><li><a href="https://github.com/rfsaldanha/sis/issues/new" class="toc-action"><i class="bi empty"></i>Criar uma issue</a></li></ul></div></div></div></footer></body></html>
